#!/bin/sh
# Build Stage
FROM python:3.12.1-bullseye AS builder
WORKDIR /code
ADD . /code
RUN pip install --no-cache-dir -r /code/requirements.txt
RUN pip install pandas
RUN pip install pyinstaller
RUN pyinstaller -F --collect-all dateutil main.py

# Runtime
FROM ubuntu:22.04 AS runtime
WORKDIR /app
COPY --from=builder /code/dist/main .
ENTRYPOINT ["./main"]